"""Patient application package."""

from src.application.patient.dtos import (
    RegisterPatientRequest,
    UpdatePatientRequest,
    RegisterDeviceRequest,
    UpdateNotificationPreferencesRequest,
    AddMedicalHistoryRequest,
    SetInquiryRequest,
    BlockPatientRequest,
    MergePatientsRequest,
    SearchPatientsRequest,
    RegisterPatientResponse,
    PatientResponse,
    PatientListResponse,
    DeviceRegisteredResponse,
    DeviceRemovedResponse,
    NotificationPreferencesResponse,
    InquiryResponse,
    PatientStatusChangeResponse,
    MergeResponse,
    ErrorResponse,
    Gender,
    PatientStatusEnum,
)
from src.application.patient.use_cases import (
    RegisterPatientUseCase,
    LookupPatientUseCase,
    UpdatePatientUseCase,
    DeviceRegistrationUseCase,
    VisitTrackingUseCase,
    MedicalHistoryUseCase,
)

__all__ = [
    # DTOs
    "RegisterPatientRequest",
    "UpdatePatientRequest",
    "RegisterDeviceRequest",
    "UpdateNotificationPreferencesRequest",
    "AddMedicalHistoryRequest",
    "SetInquiryRequest",
    "BlockPatientRequest",
    "MergePatientsRequest",
    "SearchPatientsRequest",
    "RegisterPatientResponse",
    "PatientResponse",
    "PatientListResponse",
    "DeviceRegisteredResponse",
    "DeviceRemovedResponse",
    "NotificationPreferencesResponse",
    "InquiryResponse",
    "PatientStatusChangeResponse",
    "MergeResponse",
    "ErrorResponse",
    "Gender",
    "PatientStatusEnum",
    # Use Cases
    "RegisterPatientUseCase",
    "LookupPatientUseCase",
    "UpdatePatientUseCase",
    "DeviceRegistrationUseCase",
    "VisitTrackingUseCase",
    "MedicalHistoryUseCase",
]
