"""Base value object with structural equality.

All value objects across all engines inherit from this.
Value objects are immutable and compared by their attributes, not identity.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class BaseValueObject:
    """Base class for all value objects.

    Features:
    - Frozen (immutable) — cannot be modified after creation
    - Equality by field values (auto-generated by frozen dataclass)
    - Hashable — can be used in sets and as dict keys
    """

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, BaseValueObject):
            return NotImplemented
        return self.__dict__ == other.__dict__

    def __hash__(self) -> int:
        return hash(tuple(sorted(self.__dict__.items())))
